name: holiday_jp
description: Get holidays in Japan. This library uses holiday_jp as Japanese holiday dataset.
version: 0.0.4
homepage: https://github.com/wapa5pow/holiday_jp-dart

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  intl: ^0.18.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  yaml: ^3.1.1
