name: latest_holiday_jp

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  job-test:
    name: Latest holiday_jp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3
      - run: dart pub get
      - run: ./tool/update_holidays.sh
      - run: git diff --exit-code
